### ISSUE TITLE
Support for multi-lingual / localized metadata

### ISSUE THREAD

**Issue by eblondel** [eblondel/geometa#104]
Features to implement:
- [x] gmd:PT_Locale --> ``ISOLocale``
- [x] gmd:Country -- ``ISOCountry``
- [x] gmd:PT_FreeText --> ``ISOFreeText``
- [x] gmd:LocalisedCharacterString --> ``ISOLocalisedCharacterString``
- [x] generic XML encoder enhancements
- [x] generic XML decoder enhancements
- [x] localised property management
- [x] propagation of localised property management to all concerned class/fields

Web integration tests:
- [x] CSW Insert/Update operations with [ows4R](https://github.com/eblondel/ows4R/issues/21) on **pycsw**
- [x] CSW Insert/Update operations with [ows4R](https://github.com/eblondel/ows4R/issues/21) on **Geonetwork**
- [x] Geonetwork API Insert/Update operations with [geonapi](https://github.com/eblondel/geonapi/issues/5)

**Comment by eblondel** [comment]
Fixed with https://github.com/eblondel/geometa/commit/ee28fd89b966668286204592097283c986be031b

**Comment by eblondel** [comment]
The transaction of geometa multilingual metadata sheets has been successfuly tested on both **pycsw** and **geonetwork** CSW servers (https://github.com/eblondel/ows4R/issues/21). Using the Geonetwork API (https://github.com/eblondel/geonapi/5), the insert of metadata fails (internal server error), further investigation to be done whether it is an issue of Geonetwork or with the http request sent to Geonetwork by geonapi
