### ISSUE TITLE
ISO 19115-2:2009 Content Information classes

### ISSUE THREAD

**Issue by eblondel** [eblondel/geometa#151]
- [x] MI_Band --> ``ISOImageryBand``
- [x] MI_CoverageDescription --> ``ISOImageryCoverageDescription``
- [x] MI_ImageDescription --> ``ISOImageryImageDescription``
- [x] MI_RangeElementDescription --> ``ISOImageryRangeElementDescription``
- [x] MI_BandDefinition --> ``ISOImageryBandDefinition`` (Done with #150)
- [x] MI_PolarisationOrientationCode --> ``ISOImageryPolarisationOrientation`` (Done with #150)
- [x] MI_TransferFunctionTypeCode --> ``ISOImageryTransferFunctionType`` (Done with #150)
