### ISSUE TITLE
Support for FC_FeatureType

### ISSUE THREAD

**Issue by eblondel** [eblondel/geometa#22]
- [x] Support of LocalName – [#24](https://github.com/eblondel/geometa/issues/24) 
- [x] Support of PropertType – [#25](https://github.com/eblondel/geometa/issues/25) 
- [x] Support of FeatureAttribute – [#28](https://github.com/eblondel/geometa/issues/28) 
- [x] Support of FeatureOperation – [#29](https://github.com/eblondel/geometa/issues/29)
- [x] Support of FeatureType – present ticket
