### ISSUE TITLE
Support of FeatureAttribute

### ISSUE THREAD

**Issue by eblondel** [eblondel/geometa#28]
- [x] Support of TypeName – [#31](https://github.com/eblondel/geometa/issues/31)
- [x] Support of FC_ListedValue – [#33](https://github.com/eblondel/geometa/issues/33)
- [x] Support of GML units elements – #55
- [x] Support of FeatureAttribute – present ticket
