### ISSUE TITLE
Support of MD_CoverageDescription

### ISSUE THREAD

**Issue by eblondel** [eblondel/geometa#43]
- [x] Support of RecordType – [#44](https://github.com/eblondel/geometa/issues/44)
- [x] Support of MD_CoverageContentType – [#45](https://github.com/eblondel/geometa/issues/45)
- [x] Support of MD_RangeDimension – [#46](https://github.com/eblondel/geometa/issues/46)
- [x] Support of MD_Band – [#47](https://github.com/eblondel/geometa/issues/47)
- [x] Support of MD_CoverageDescription – present ticket
