### ISSUE TITLE
Support configuration of ISO 19115/19119 profiles

### ISSUE THREAD

**Issue by eblondel** [eblondel/geometa#92]
- [x] #87 Add geometa options management
- [x] #88 Support ``ISOCodelist`` registration (create, update)
- [x] #89 Support ``ISOMetadataNamespace`` registration
- [x] #90 Support custom schema registration (create, update)
- [x] Support decoding operation of custom ISO Profile classes
